# Generated by Django 5.0.6 on 2024-07-01 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('retirada', models.CharField(blank=True, max_length=200, null=True, verbose_name='retirada do produto')),
                ('situacao_retirada', models.BooleanField(default=False, verbose_name='se o pedido foi entregue ou não')),
                ('data_retirada', models.DateTimeField(blank=True, null=True, verbose_name='data de retirada do produto')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_contato', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ordem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('imagem', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images/', verbose_name='imagem do produto')),
                ('marca', models.CharField(blank=True, max_length=200, null=True, verbose_name='marca do produto')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, verbose_name='categoria do produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição do produto')),
                ('reviews', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='avaliação do produto')),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='numero de avaliações')),
                ('estoque', models.IntegerField(blank=True, default=0, null=True, verbose_name='numero de produtos em estoque')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('imagem', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ordem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='nome')),
                ('reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='avaliação do produto')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='comentarios do produto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
